;;; init-cachedir.el --- create variable of my-cache-dir and ensure folder
;;; exists.

;;; Commentary:
;;; Code:

(defvar my-cache-dir (concat user-emacs-directory "cache/")
  "Folder to save temperary files generated by Emacs.")
(unless (file-exists-p my-cache-dir)
    (make-directory my-cache-dir t))

(provide 'init-cachedir)
;;; init-cachedir.el ends here
